"""crear esquema inicial

Revision ID: 9b9f04eb67f6
Revises: 
Create Date: 2026-09-27 22:01:19.257324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9f04eb67f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id_configuracion', sa.Integer(), nullable=False),
    sa.Column('separacion_mm', sa.Float(), nullable=False),
    sa.Column('margen_mm', sa.Float(), nullable=False),
    sa.Column('resolucion_raster', sa.Float(), nullable=False),
    sa.Column('paso_angular', sa.Float(), nullable=False),
    sa.Column('area_minima_retazo', sa.Float(), nullable=False),
    sa.Column('dimension_minima_retazo', sa.Float(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_configuracion')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_vidrio',
    sa.Column('id_tipo_vidrio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_vidrio')
    )
    op.create_table('planchas',
    sa.Column('id_plancha', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('ancho_mm', sa.Float(), nullable=False),
    sa.Column('alto_mm', sa.Float(), nullable=False),
    sa.Column('espesor_mm', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_tipo_vidrio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_vidrio'], ['tipos_vidrio.id_tipo_vidrio'], ),
    sa.PrimaryKeyConstraint('id_plancha'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('retazos',
    sa.Column('id_retazo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('espesor_mm', sa.Float(), nullable=False),
    sa.Column('geometria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('area_mm2', sa.Float(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_tipo_vidrio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_vidrio'], ['tipos_vidrio.id_tipo_vidrio'], ),
    sa.PrimaryKeyConstraint('id_retazo'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('espesor_mm', sa.Float(), nullable=False),
    sa.Column('id_tipo_vidrio', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_vidrio'], ['tipos_vidrio.id_tipo_vidrio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('ejecuciones_optimizacion',
    sa.Column('id_ejecucion', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=False),
    sa.Column('tiempo_computacional', sa.Float(), nullable=True),
    sa.Column('seleccionada', sa.Boolean(), nullable=False),
    sa.Column('patron_resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_configuracion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_configuracion'], ['configuraciones.id_configuracion'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_ejecucion')
    )
    op.create_table('piezas',
    sa.Column('id_pieza', sa.Integer(), nullable=False),
    sa.Column('tipo_forma', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('dimensiones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geometria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area_mm2', sa.Float(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_pieza')
    )
    op.create_table('metricas_ejecucion',
    sa.Column('id_metrica', sa.Integer(), nullable=False),
    sa.Column('aprovechamiento_pct', sa.Float(), nullable=True),
    sa.Column('merma_mm2', sa.Float(), nullable=True),
    sa.Column('planchas_utilizadas', sa.Integer(), nullable=True),
    sa.Column('area_recuperable_mm2', sa.Float(), nullable=True),
    sa.Column('tiempo_computacional_ms', sa.Float(), nullable=True),
    sa.Column('id_ejecucion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ejecucion'], ['ejecuciones_optimizacion.id_ejecucion'], ),
    sa.PrimaryKeyConstraint('id_metrica'),
    sa.UniqueConstraint('id_ejecucion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_ejecucion')
    op.drop_table('piezas')
    op.drop_table('ejecuciones_optimizacion')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    op.drop_table('retazos')
    op.drop_table('planchas')
    op.drop_table('tipos_vidrio')
    op.drop_table('roles')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
